name: 'Azure Resource Creation'

on:
  repository_dispatch:
    types: [workato-trigger]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.event.client_payload.working_directory }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.10.3

    - name: Azure Login with OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Create variables file
      id: variables-create
      run: echo '${{ toJson(github.event.client_payload.variables) }}' > ./${{ github.event.client_payload.working_directory }}/variables.tfvars.json

    - name: Initialize Terraform
      run: |
        terraform init \
          -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT }}" \
          -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" \
          -backend-config="resource_group_name=${{ secrets.RESOURCE_GROUP_NAME }}" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
          -backend-config="tenant_id=${{ secrets.AZURE_TENANT_ID }}"
  
    - name: Apply or Destroy Terraform
      run: |
        if [ "${{ github.event.client_payload.action }}" == "destroy" ]; then
          terraform destroy -auto-approve
        else
          terraform apply -auto-approve -var-file=variables.tfvars.json
        fi
      env:
        TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}

    - name: Remove state file from Azure Backend (Only on Destroy)
      if: github.event.client_payload.action == 'destroy'
      run: |
        az storage blob delete -c ${{ secrets.CONTAINER_NAME }} -n terraform.tfstate --account-name marktfstate --auth-mode login

    # - name: Send output to webhook
    #   if: always()
    #   run: |
    #     if [ -z "${{ env.output }}" ]; then
    #       output="Terraform output not available"
    #     else
    #       output="${{ env.output }}"
    #     fi
    #     curl -X POST -H "Content-Type: application/json" \
    #     -d "{\"output\": ${output}, \"status\": \"${{ job.status }}\"}" \
    #     https://webhooks.workato.com/webhooks/rest/855bb7a0-ec04-4752-8022-044be408d270/github-action-output
