name: 'Azure User Creation'

on:
  repository_dispatch:
    types: [workato-trigger]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./azure_users
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.10.3

    - name: Azure Login with OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set environment variables for Terraform backend
      run: |
        echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
        echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV

    - name: Initialize Terraform
      # env:
      #   ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      #   ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      #   ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
      run: |
        terraform init \
          -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT }}" \
          -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" \
          -backend-config="resource_group_name=${{ secrets.RESOURCE_GROUP_NAME }}" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
          -backend-config="tenant_id=${{ secrets.AZURE_TENANT_ID }}"
  
    - name: Apply Terraform
      run: terraform apply -auto-approve
      env:
        TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
        TF_VAR_new_user: ${{ github.event.client_payload.username }}

    # - name: Send output to webhook
    #   if: always()
    #   run: |
    #     if [ -z "${{ env.output }}" ]; then
    #       output="Terraform output not available"
    #     else
    #       output="${{ env.output }}"
    #     fi
    #     curl -X POST -H "Content-Type: application/json" \
    #     -d "{\"output\": ${output}, \"status\": \"${{ job.status }}\"}" \
    #     https://webhooks.workato.com/webhooks/rest/855bb7a0-ec04-4752-8022-044be408d270/github-action-output
