name: 'Azure User Creation'

on:
  repository_dispatch:
    types: [workato-trigger]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./azure_users
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.10.3

    - name: Azure Login with OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform
      run: terraform apply -auto-approve
      env:
        TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
        TF_VAR_new_user: ${{ github.event.client_payload.username }}

    # - name: Send output to webhook
    #   if: always()
    #   run: |
    #     if [ -z "${{ env.output }}" ]; then
    #       output="Terraform output not available"
    #     else
    #       output="${{ env.output }}"
    #     fi
    #     curl -X POST -H "Content-Type: application/json" \
    #     -d "{\"output\": ${output}, \"status\": \"${{ job.status }}\"}" \
    #     https://webhooks.workato.com/webhooks/rest/855bb7a0-ec04-4752-8022-044be408d270/github-action-output
