name: Test Action Test

on:
  workflow_dispatch:
      
env:
  TF_BACKEND_BUCKET: "terraform-state-strore"
  TF_BACKEND_REGION: "us-east-1"      

permissions:
  id-token: write
  contents: read
  actions: read
  security-events: write         

jobs:
  state: 
    name: Terraform State Output
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Configure AWS credentials Role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_GITHUB_ACTION_ROLE }}
        aws-region: ${{ env.TF_BACKEND_REGION }}
        
    
    - name: Initialize Terraform
      run: |
          terraform init \
          -backend-config="bucket=${{ env.TF_BACKEND_BUCKET }}" \
          -backend-config="region=${{ env.TF_BACKEND_REGION }}" \
          -backend-config="key=s3/FEDE-001/tf-state"
      working-directory: ./aws/s3

    - name: Terraform Output
      run: |
          echo $output
      working-directory: ./aws/s3

    - name: Curl call
      run: |
        curl -X POST --data-urlencode "${{ env.output }}" "https://webhooks.workato.com/webhooks/rest/855bb7a0-ec04-4752-8022-044be408d270/get-callback"
        
