name: Test Action Test

on:
  workflow_dispatch:
    inputs:
      request_id:
        description: 'Jira Ticket Id'
        required: true
        type: string     
env:
  TF_BACKEND_BUCKET: "terraform-state-strore"
  TF_BACKEND_REGION: "us-east-1"      

permissions:
  id-token: write
  contents: read
  actions: read
  security-events: write         

jobs:
  state: 
    name: Terraform State Output
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Configure AWS credentials Role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_GITHUB_ACTION_ROLE }}
        aws-region: ${{ env.TF_BACKEND_REGION }}
        
    
    - name: Initialize Terraform
      run: |
          terraform init \
          -backend-config="bucket=${{ env.TF_BACKEND_BUCKET }}" \
          -backend-config="region=${{ env.TF_BACKEND_REGION }}" \
          -backend-config="key=s3/${{ github.event.inputs.request_id }}/tf-state"
      working-directory: ./aws/s3

    - name: Force Error
      run: exit 1

    - name: Terraform Output
      id: terraform_output
      run: |
          echo "$(terraform output -json)" | jq '{"jira_key":"${{ github.event.inputs.request_id }}", "terraform_action": "testing", "output": map_values(.value)}'> terraform_output.json
          cat terraform_output.json
      working-directory: ./aws/s3

    - name: Build Error Message
      if: ${{ failure() || cancelled() }}
      run: |
        jq -cn '{"jira_key": "${{ github.event.inputs.request_id }}", "terraform_action": "testing", "output": {"message": "Process Failed or Cancelled. Please check process ${{ github.job_id }}"}}'> terraform_output.json
        echo $(cat terraform_output.json)
      working-directory: ./aws/s3

    - name: Curl call
      if: always()
      run: |
        curl -X POST -H 'Content-Type: application/json' -d @./aws/s3/terraform_output.json "https://webhooks.workato.com/webhooks/rest/855bb7a0-ec04-4752-8022-044be408d270/get-callback"
        
